Repository aura-nw/horoscope-v2, pull requests merged in 2023-12, with the labels that each got.

#509 Feat/coin transfer staging
  ci/config.json.ci
  config.json
  hasura/metadata/databases/auratestnet/tables/public_coin_transfer.yaml
  hasura/metadata/databases/euphoria/tables/public_coin_transfer.yaml
  hasura/metadata/databases/euphoria/tables/tables.yaml
  hasura/metadata/databases/pion/tables/tables.yaml
  hasura/metadata/databases/serenity/tables/public_coin_transfer.yaml
  hasura/metadata/databases/serenity/tables/tables.yaml
  hasura/metadata/databases/xstaxy/tables/public_coin_transfer.yaml
  hasura/metadata/databases/xstaxy/tables/tables.yaml
  migrations/20231110031644_create_coin_transfer_table.ts
  src/common/constant.ts
  src/models/block_checkpoint.ts
  src/models/coin_transfer.ts
  src/models/index.ts
  src/services/crawl-tx/coin_transfer.service.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/multiple_tx_coin_transfer.json
  test/unit/services/crawl-transaction/single_tx_coin_transfer.json
Labels: staging

#516 Feat/coin transfer main
  ci/config.json.ci
  config.json
  migrations/20231110031644_create_coin_transfer_table.ts
  src/common/constant.ts
  src/models/block_checkpoint.ts
  src/models/coin_transfer.ts
  src/models/index.ts
  src/services/crawl-tx/coin_transfer.service.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/multiple_tx_coin_transfer.json
  test/unit/services/crawl-transaction/single_tx_coin_transfer.json
Labels: main

#515 fix: remove not used create contraint command when start job
  src/services/job/create_constraint_in_attr_partition.service.ts
Labels: main

#519 fix: update query drop constraint in attr partition
  src/services/job/create_constraint_in_attr_partition.service.ts
Labels: main

#522 Feat: job create constraint for event table
  config.json
  src/common/constant.ts
  src/services/job/create_constraint_in_event_partition.service.ts
Labels: develop

#523 feat: separate migration for development and staging environtment
  migrations/20231018090129_refactor_transaction_index.ts
  migrations/20231018092805_refactor_event_index.ts
  migrations/20231019031350_drop_old_btree_index_event.ts
  migrations/20231019031400_drop_old_btree_index_transaction.ts
  migrations/20231019034210_create_brin_index_event_atttribute.ts
  migrations/20231019034225_drop_btree_index_event_atttribute.ts
  migrations/20231121021951_create_table_event_partition.ts
  src/common/constant.ts
Labels: develop

#524 Fix smart contract event stg
  src/common/utils/smart_contract.ts
  src/services/cw20/cw20.service.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: staging

#525 Fix/fix create constraint
  src/services/job/create_constraint_in_event_partition.service.ts
Labels: develop

#486 chore: replace yarn with npm
  .github/workflows/test.yml
  .husky/pre-push
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/common/types/interfaces.ts
  src/common/utils/aurajs_client.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-proposal/crawl_proposal.service.ts
  src/services/crawl-proposal/crawl_tally_proposal.service.ts
  src/services/crawl-tx/aura.registry.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-validator/crawl_delegators.service.ts
  src/services/crawl-validator/crawl_signing_info.service.ts
  src/services/crawl-validator/crawl_validator.service.ts
  src/services/statistics/dashboard_statistics.service.ts
  yarn.lock
Labels: develop

#530 Feat/transaction partition
  ci/config.json.ci
  config.json
  migrations/20231129081016_partition-transaction-table.ts
  src/common/constant.ts
  src/services/job/create_transaction_partition.service.ts
  test/unit/services/job/create_table_event_partition.spec.ts
  test/unit/services/job/create_table_transaction_partition.spec.ts
Labels: develop

#534 Fix add constraint on exist table
  migrations/20231129081016_partition-transaction-table.ts
Labels: develop

#536 feat: remove column signature in block_signature table
  migrations/20231020083123_remove_column_signature_in_block_signature.ts
  src/models/block_signature.ts
  src/services/crawl-block/crawl_block.service.ts
Labels: main

#540 fix: avoid lock all table while run transaction partition migration
  migrations/20231129081016_partition-transaction-table.ts
Labels: develop

#492 fix: skip proposal if not found onchain
  src/services/crawl-proposal/crawl_proposal.service.ts
Labels: main

#545 fix: update seq for transaction partitioned
  migrations/20231129081016_partition-transaction-table.ts
Labels: develop

#547 Feat/update smart account (develop)
  src/common/constant.ts
  src/services/crawl-tx/registry-type/aura-network.json
Labels: develop

#548 Fix/update cw20 query (develop)
  src/services/cw20/cw20.service.ts
Labels: develop

#550 Fix/update cw721 query (develop)
  src/models/cw721_tx.ts
Labels: develop

#546 fix: add authz handle in coin_transfer (develop)
  package.json
  src/services/crawl-tx/coin_transfer.service.ts
  test/unit/services/crawl-transaction/authz_tx_coin_transfer.json
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
Labels: develop

#544 fix: update query in handle stake event (develop)
  src/services/crawl-validator/handle_stake_event.service.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
Labels: develop

#553 Fix/sei chain testnet sc
  ci/config.json.ci
  config.json
  hasura/metadata/databases/xstaxy/tables/public_smart_contract_event.yaml
  migrations/20231129081016_partition-transaction-table.ts
  migrations/20231219084332_update-for-sei-chain.ts
  network.json
  src/common/constant.ts
  src/common/index.ts
  src/common/utils/helper.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/chain.registry.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-tx/registry-type/aura-network.json
  src/services/crawl-tx/sei.registry.ts
  src/services/cw20/cw20.service.ts
  src/services/job/reassign_msg_index_to_event.service.ts
  src/services/job/redecode_tx.service.ts
  test/unit/services/crawl-account/crawl_account.spec.ts
  test/unit/services/crawl-account/handle_address.spec.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-cosmwasm/crawl_smart_contract.spec.ts
  test/unit/services/crawl-proposal/crawl_proposal.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/crawl-validator/crawl_validator.spec.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
  test/unit/services/handle-vote/handle_vote.spec.ts
  test/unit/services/ibc/crawl_ibc_tao.spec.ts
  test/unit/services/job/reassign_msg_index_to_event.spec.ts
Labels: sei

#532 Fix/improve crawl delegator (main)
  src/services/crawl-validator/crawl_delegators.service.ts
  test/unit/services/crawl-validator/crawl_delegators.spec.ts
Labels: main

#557 feat: update auranw to aura; use aurajs@0.1.7, jest-mock@29.5.0 (main)
  .github/workflows/test.yml
  .husky/pre-push
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/common/types/interfaces.ts
  src/common/utils/aurajs_client.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-proposal/crawl_proposal.service.ts
  src/services/crawl-proposal/crawl_tally_proposal.service.ts
  src/services/crawl-tx/aura.registry.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-validator/crawl_delegators.service.ts
  src/services/crawl-validator/crawl_signing_info.service.ts
  src/services/crawl-validator/crawl_validator.service.ts
  src/services/statistics/dashboard_statistics.service.ts
  yarn.lock
Labels: main

#558 fix: update hasura for transaction partitioned
  hasura/metadata/databases/auratestnet/tables/public_event.yaml
  hasura/metadata/databases/auratestnet/tables/public_event_attribute.yaml
  hasura/metadata/databases/auratestnet/tables/public_feegrant.yaml
  hasura/metadata/databases/auratestnet/tables/public_feegrant_history.yaml
  hasura/metadata/databases/auratestnet/tables/public_power_event.yaml
  hasura/metadata/databases/auratestnet/tables/public_transaction_message.yaml
  hasura/metadata/databases/auratestnet/tables/public_vote.yaml
  hasura/metadata/databases/euphoria/tables/public_event.yaml
  hasura/metadata/databases/euphoria/tables/public_event_attribute.yaml
  hasura/metadata/databases/euphoria/tables/public_feegrant.yaml
  hasura/metadata/databases/euphoria/tables/public_feegrant_history.yaml
  hasura/metadata/databases/euphoria/tables/public_power_event.yaml
  hasura/metadata/databases/euphoria/tables/public_transaction_message.yaml
  hasura/metadata/databases/euphoria/tables/public_vote.yaml
  hasura/metadata/databases/nois/tables/public_event.yaml
  hasura/metadata/databases/nois/tables/public_event_attribute.yaml
  hasura/metadata/databases/nois/tables/public_feegrant.yaml
  hasura/metadata/databases/nois/tables/public_feegrant_history.yaml
  hasura/metadata/databases/nois/tables/public_power_event.yaml
  hasura/metadata/databases/nois/tables/public_transaction_message.yaml
  hasura/metadata/databases/nois/tables/public_vote.yaml
  hasura/metadata/databases/serenity/tables/public_event.yaml
  hasura/metadata/databases/serenity/tables/public_event_attribute.yaml
  hasura/metadata/databases/serenity/tables/public_feegrant.yaml
  hasura/metadata/databases/serenity/tables/public_feegrant_history.yaml
  hasura/metadata/databases/serenity/tables/public_power_event.yaml
  hasura/metadata/databases/serenity/tables/public_transaction_message.yaml
  hasura/metadata/databases/serenity/tables/public_vote.yaml
  hasura/metadata/databases/xstaxy/tables/public_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_event_attribute.yaml
  hasura/metadata/databases/xstaxy/tables/public_feegrant.yaml
  hasura/metadata/databases/xstaxy/tables/public_feegrant_history.yaml
  hasura/metadata/databases/xstaxy/tables/public_power_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_transaction_message.yaml
  hasura/metadata/databases/xstaxy/tables/public_vote.yaml
Labels: develop

#556 Fix/update cw20 cw721 query (main)
  src/models/cw721_tx.ts
  src/services/cw20/cw20.service.ts
Labels: main

#554 Fix/add authz to coin transfer (staging)
  package.json
  src/services/crawl-tx/coin_transfer.service.ts
  test/unit/services/crawl-transaction/authz_tx_coin_transfer.json
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
Labels: staging

#559 feat: Ibc statistic main
  config.json
  hasura/metadata/databases/auratestnet/tables/m_view_ibc_relayer_statistic.yaml
  hasura/metadata/databases/auratestnet/tables/view_ibc_channel_detail_statistic.yaml
  hasura/metadata/databases/euphoria/tables/m_view_ibc_relayer_statistic.yaml
  hasura/metadata/databases/euphoria/tables/view_ibc_channel_detail_statistic.yaml
  hasura/metadata/databases/nois/tables/m_view_ibc_relayer_statistic.yaml
  hasura/metadata/databases/nois/tables/view_ibc_channel_detail_statistic.yaml
  hasura/metadata/databases/sei/tables/m_view_ibc_relayer_statistic.yaml
  hasura/metadata/databases/sei/tables/view_ibc_channel_detail_statistic.yaml
  hasura/metadata/databases/serenity/tables/m_view_ibc_relayer_statistic.yaml
  hasura/metadata/databases/serenity/tables/view_ibc_channel_detail_statistic.yaml
  hasura/metadata/databases/xstaxy/tables/m_view_ibc_relayer_statistic.yaml
  hasura/metadata/databases/xstaxy/tables/view_ibc_channel_detail_statistic.yaml
  migrations/20231122062744_create_m_view_ibc_relayer_statistic.ts
  migrations/20231123024441_create_view_ibc_channel_detail_statistic.ts
  src/common/constant.ts
  src/services/ibc/ibc_statistic.service.ts
Labels: main

#563 Fix/aurajs client
  package-lock.json
  package.json
  src/common/types/interfaces.ts
  src/common/utils/aurajs_client.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-proposal/crawl_proposal.service.ts
  src/services/crawl-proposal/crawl_tally_proposal.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-validator/crawl_delegators.service.ts
  src/services/crawl-validator/crawl_signing_info.service.ts
  src/services/crawl-validator/crawl_validator.service.ts
  src/services/statistics/dashboard_statistics.service.ts
Labels: sei

#565 fix: fix provider rpc for sei follow latest version of sei cosmos
  package-lock.json
  package.json
Labels: sei
