Repository aura-nw/horoscope-v2, pull requests merged in 2024-06, with the labels that each got.

#809 fix: create evm smart contract from internal tx
  src/models/evm_internal_transaction.ts
  src/models/evm_transaction.ts
  src/services/evm/crawl_contract_evm.service.ts
Labels: bug, develop

#807 Feat/reindex batch erc721
  network.json
  src/models/erc721_contract.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/erc721_admin.service.ts
  src/services/evm/constant.ts
  src/services/evm/erc721.service.ts
  src/services/evm/erc721_handler.ts
  src/services/evm/erc721_reindex.ts
  test/unit/services/erc721/erc721.spec.ts
  test/unit/services/erc721/erc721_handler.spec.ts
Labels: develop

#813 Fix/create evm smart contract from internal tx
  src/models/evm_internal_transaction.ts
  src/models/evm_transaction.ts
  src/services/evm/crawl_contract_evm.service.ts
Labels: bug, staging

#814 fix: use lib @shazow/whatsabi to get selector
  package-lock.json
  package.json
  src/services/evm/crawl_contract_evm.service.ts
Labels: develop

#812 fix: crawl internal tx call error
  migrations/evm/20240613070822_evm_internal_transaction_add_error_col.ts
  src/models/evm_internal_transaction.ts
  src/services/evm/evm_crawl_internal_tx.service.ts
Labels: bug, develop

#820 Fix/crawl internal tx call error staging
  migrations/evm/20240613070822_evm_internal_transaction_add_error_col.ts
  src/models/evm_internal_transaction.ts
  src/services/evm/evm_crawl_internal_tx.service.ts
Labels: staging

#819 Refactor/repalce etherjs by viem staging
  package-lock.json
  package.json
  src/common/utils/etherjs_client.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc721.service.ts
  src/services/evm/evm_proxy.service.ts
  src/services/evm/handle_tx_evm.service.ts
  src/services/evm/helpers/contract_helper.ts
  src/services/evm/verify_contract_evm.service.ts
  test/unit/services/evm/evm_proxy.spec.ts
Labels: staging

#817 fix: use lib @shazow/whatsabi to get selector
  package-lock.json
  package.json
  src/services/evm/crawl_contract_evm.service.ts
Labels: staging

#816 feat: add setting to evm contract verification merge staging
  hasura/metadata/databases/euphoria/tables/public_evm_contract_verification.yaml
  migrations/evm/20240611034019_add_compile_setting_to_evm_contract_verification.ts
  src/models/evm_contract_verification.ts
  src/services/evm/job/sync_sourcify.service.ts
  src/services/evm/verify_contract_evm.service.ts
Labels: staging

#821 fix: use lib @shazow/whatsabi to get selector
  package-lock.json
  package.json
  src/services/evm/crawl_contract_evm.service.ts
Labels: main

#824 Fix/create evm smart contract from internal tx main
  src/models/evm_internal_transaction.ts
  src/models/evm_transaction.ts
  src/services/evm/crawl_contract_evm.service.ts
Labels: main

#823 feat: add setting to evm contract verification merge main
  hasura/metadata/databases/xstaxy/tables/public_evm_contract_verification.yaml
  migrations/evm/20240611034019_add_compile_setting_to_evm_contract_verification.ts
  src/models/evm_contract_verification.ts
  src/services/evm/job/sync_sourcify.service.ts
  src/services/evm/verify_contract_evm.service.ts
Labels: main
