Repository aura-nw/horoscope-v2, pull requests merged in 2024-08, with the labels that each got.

#878 Feat/merge erc20 from develop to evm
  migrations/evm/20240702013020_add_col_to_save_cosmos_erc20.ts
  src/models/account_balance.ts
  src/models/erc20_activity.ts
  src/models/event.ts
  src/models/event_attribute.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/erc20_admin.service.ts
  src/services/evm/constant.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  src/services/evm/erc20_reindex.ts
  test/unit/services/erc20/erc20.spec.ts
  test/unit/services/erc20/erc20_handler.spec.ts
  test/unit/services/evm/erc20.spec.ts
  test/unit/services/evm/erc20_handler.spec.ts
  test/unit/services/evm/erc20_reindex.spec.ts
Labels: evm

#859 feat: insert contract optimism verification
  script/insert_op_stack_abi/abis/l1_block.json
  script/insert_op_stack_abi/abis/l2_cross_domain_messenger.json
  script/insert_op_stack_abi/abis/l2_standard_bridge.json
  script/insert_op_stack_abi/abis/l2_to_l1_message_passer.json
  script/insert_op_stack_abi/abis/proxy.json
  script/insert_op_stack_abi/index.ts
Labels: evm

#879 feat: erc20 reindex too big contract
  ci/config.json.ci
  config.json
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  src/services/evm/erc20_reindex.ts
Labels: evm

#877 feat: add detect proxy eip 1167
  src/models/evm_smart_contract.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/helpers/contract_helper.ts
Labels: develop

#882 fix: erc721 reindex stats
  src/services/evm/erc721_handler.ts
  src/services/evm/erc721_reindex.ts
Labels: evm

#880 fix: proxy_contract not found on evm_smart_contract
  src/services/evm/crawl_evm_proxy_history.service.ts
Labels: develop

#885 fix: proxy contract not found
  src/services/evm/crawl_evm_proxy_history.service.ts
Labels: staging

#886 fix: proxy contract not found
  src/services/evm/crawl_evm_proxy_history.service.ts
Labels: main

#869 refactor: erc20 activity transfer amount in topic3
  src/services/evm/erc20_handler.ts
  test/unit/services/evm/erc20_handler.spec.ts
Labels: develop

#884 feat: add proxy eip 1167 to refactor crawl evm smart contract
  src/models/evm_smart_contract.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/helpers/contract_helper.ts
Labels: staging

#891 refactor: evm proxy history batch query bytecode
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/helpers/contract_helper.ts
Labels: evm

#892 refactor: optimise proxy history
  src/services/evm/crawl_evm_proxy_history.service.ts
Labels: evm
