Repository aura-nw/horoscope-v2, pull requests merged in 2024-05, with the labels that each got.

#774 fix: null token id (case approval all)
  src/services/evm/erc721.service.ts
Labels: bug, develop

#783 fix: erc20 proxy activity
  src/services/evm/erc20.service.ts
Labels: bug, staging

#784 Feat/erc721 media info
  ci/config.json.ci
  config.json
  migrations/evm/20240506022938_erc721_media_info.ts
  src/models/erc721_contract.ts
  src/models/erc721_token.ts
  src/models/index.ts
  src/services/evm/constant.ts
  src/services/evm/erc721.service.ts
  src/services/evm/erc721_handler.ts
  src/services/evm/erc721_media_handler.ts
  test/unit/services/erc721/erc721-media.spec.ts
Labels: develop

#785 feat: sync db sourcify
  .env.sample
  ci/config.json.ci
  config.json
  knexfile.ts
  src/common/utils/db_connection_sourcify.ts
  src/models/evm_contract_verification.ts
  src/models/sourcify/base.ts
  src/models/sourcify/code.ts
  src/models/sourcify/compiled_contract.ts
  src/models/sourcify/contract.ts
  src/models/sourcify/contract_deployment.ts
  src/models/sourcify/index.ts
  src/models/sourcify/sourcify_match.ts
  src/models/sourcify/verified_contract.ts
  src/services/evm/constant.ts
  src/services/evm/job/sync_sourcify.service.ts
Labels: develop

#786 feat: erc721 statistic
  ci/config.json.ci
  config.json
  migrations/evm/20240510020548_erc721_stats.ts
  src/models/erc721_activity.ts
  src/models/erc721_contract.ts
  src/models/erc721_stats.ts
  src/models/index.ts
  src/services/evm/constant.ts
  src/services/evm/erc721.service.ts
  test/unit/services/erc721/erc721.spec.ts
Labels: develop

#792 feat: erc721 view count holder
  migrations/evm/20240517102045_view_count_holder_erc721.ts
Labels: develop

#794 feat: crawl evm block
  ci/config.json.ci
  config.json
  migrations/evm/20240517090021_create_evm_block.ts
  src/models/evm_block.ts
  src/models/index.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_block.service.ts
  src/services/evm/job/create_constraint_in_evm_block_partition.service.ts
  src/services/evm/job/create_evm_block_partition.service.ts
  test/unit/services/job/create_table_evm_block_partition.spec.ts
Labels: evm

#796 feat: crawl evm tx
  ci/config.json.ci
  config.json
  migrations/evm/20240520075600_add_col_save_evm_only.ts
  src/models/evm_transaction.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_transaction.service.ts
Labels: evm

#795 fix: update staking precompile abi
  migrations/evm/20240520091605_update_staking_precompile_abi.ts
  src/services/evm/precompile-abis/staking.json
Labels: develop

#790 feat: create api and job insert verify by codehash
  src/models/evm_smart_contract.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/job.service.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/job/insert_verify_by_codehash.service.ts
Labels: develop

#798 fix: update staking precompile abi merge staging
  migrations/evm/20240520091605_update_staking_precompile_abi.ts
  src/services/evm/precompile-abis/staking.json
Labels: staging

#797 feat: create job sync similar code hash merge staging
  src/models/evm_smart_contract.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/job.service.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/job/insert_verify_by_codehash.service.ts
Labels: staging

#788 feat: sync db sourcify merge staging
  .env.sample
  ci/config.json.ci
  config.json
  knexfile.ts
  src/common/utils/db_connection_sourcify.ts
  src/models/evm_contract_verification.ts
  src/models/sourcify/base.ts
  src/models/sourcify/code.ts
  src/models/sourcify/compiled_contract.ts
  src/models/sourcify/contract.ts
  src/models/sourcify/contract_deployment.ts
  src/models/sourcify/index.ts
  src/models/sourcify/sourcify_match.ts
  src/models/sourcify/verified_contract.ts
  src/services/evm/constant.ts
  src/services/evm/job/sync_sourcify.service.ts
Labels: staging

#789 feat: update power event by cosmos sdk
  src/services/crawl-validator/handle_stake_event.service.ts
Labels: develop

#802 feat: add config viem
  ci/config.json.ci
  config.json
  src/common/utils/etherjs_client.ts
Labels: develop

#779 Feat/crawl erc721 activity staging
  ci/config.json.ci
  config.json
  migrations/evm/20240409065017_erc721_token_init.ts
  migrations/evm/20240409065018_erc721_activity_init.ts
  migrations/evm/20240506022938_erc721_media_info.ts
  migrations/evm/20240510020548_erc721_stats.ts
  migrations/evm/20240517102045_view_count_holder_erc721.ts
  src/models/erc721_activity.ts
  src/models/erc721_contract.ts
  src/models/erc721_stats.ts
  src/models/erc721_token.ts
  src/models/index.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc721.service.ts
  src/services/evm/erc721_handler.ts
  src/services/evm/erc721_media_handler.ts
  test/unit/services/erc721/erc721-media.spec.ts
  test/unit/services/erc721/erc721.spec.ts
  test/unit/services/evm/crawl_evm_proxy_history.spec.ts
Labels: staging

#805 Feat/evm account
  ci/config.json.ci
  config.json
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_account.service.ts
  src/services/evm/erc20.service.ts
Labels: evm

#803 feat: add config viem
  ci/config.json.ci
  config.json
  src/common/utils/etherjs_client.ts
Labels: staging

#804 feat: update power event by cosmos sdk
  src/services/crawl-validator/handle_stake_event.service.ts
Labels: staging

#708 fix: remove numberOfBlockPerCall to use blocksPerCall in crawl block, tx
  ci/config.json.ci
  config.json
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
Labels: main
