Repository aura-nw/horoscope-v2, pull requests merged in 2024-04, with the labels that each got.

#734 feat: let evm service use only evm constant; add evm job to bullboard
  src/common/constant.ts
  src/mixins/bullBoard/bullBoard.mixin.ts
  src/services/api-gateways/job.service.ts
  src/services/api-gateways/verify_contract_evm.service.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/crawl_evm_event.service.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc20.service.ts
  src/services/evm/evm_signature_mapping.service.ts
  src/services/evm/handle_tx_evm.service.ts
  src/services/evm/job/create_constraint_in_evm_event_partition.service.ts
  src/services/evm/job/create_constraint_in_evm_transaction_partition.service.ts
  src/services/evm/job/create_evm_event_partition.service.ts
  src/services/evm/job/create_evm_transaction_partition.service.ts
  src/services/evm/update_assets.service.ts
  src/services/evm/verify_contract_evm.service.ts
  test/unit/services/job/create_constraint_evm_event_partition.spec.ts
  test/unit/services/job/create_constraint_evm_transaction_partition.spec.ts
  test/unit/services/job/create_table_evm_event_partition.spec.ts
Labels: evmos

#736 feat: create composite index (sender, tx_id) in transaction_message
  migrations/20240321015030_create_composite_index_tx_id_sender_in_tx_msg.ts
Labels: evmos

#737 feat: move all evm migrations to evm folder; update knex to migrate evm
  knexfile.ts
  migrations/evm/20240227082932_create_evm_transaction_table.ts
  migrations/evm/20240227083112_evm_event.ts
  migrations/evm/20240229065959_create_evm_address_column_in_account.ts
  migrations/evm/20240305072734_create_table_evm_contract_verification.ts
  migrations/evm/20240307101458_create_evm_smart_contract.ts
  migrations/evm/20240311063708_add_col_contract_address_to_evm_tx.ts
  migrations/evm/20240311083152_evm_signature_mapping.ts
  migrations/evm/20240312040758_add_col_code_hash_to_evm_contract.ts
  migrations/evm/20240313025300_erc20_contract_init.ts
  migrations/evm/20240314041631_create_composite_index_address_evm_tx_id_in_evm_event.ts
  migrations/evm/20240314065656_create_compile_detail_evm_contract_verification.ts
  migrations/evm/20240318033224_evm_signature_mapping_add_column.ts
  migrations/evm/20240318035604_add-precompiles-comtracts.ts
  migrations/evm/20240318080922_erc20_activity_init.ts
  migrations/evm/20240320071502_evm_event_add_column.ts
  migrations/evm/20240320080140_create-evm-proxy-history.ts
  migrations/evm/20240326084123_add_unique_to_evm_proxy_history.ts
  migrations/evm/20240328035728_erc20_activity_add_evm_tx_id.ts
  migrations/evm/20240328070749_create_index_column_in_evm_tx.ts
Labels: evmos

#738 fix: fix unit test for evm event partition
  test/unit/services/job/create_constraint_evm_event_partition.spec.ts
Labels: evmos

#681 fix: hotfix account balance
  src/services/crawl-account/crawl_account.service.ts
Labels: bug, develop

#704 Feat/crawl erc721 contract
  ci/config.json.ci
  config.json
  migrations/evm/20240318035358_erc721_contract_init.ts
  src/models/erc721_contract.ts
  src/services/evm/constant.ts
  src/services/evm/erc721.service.ts
Labels: evmos

#726 Feat/erc20 account balance
  src/models/account_balance.ts
  src/models/erc20_activity.ts
  src/models/erc20_contract.ts
  src/services/crawl-account/handle_address.service.ts
  src/services/evm/constant.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  test/unit/services/erc20/erc20.spec.ts
  test/unit/services/erc20/erc20_handler.spec.ts
Labels: evmos

#655 fix: update job redecode tx with s3 (develop)
  src/services/job/redecode_tx.service.ts
Labels: develop

#744 fix: erc20 balance insert empty
  src/services/evm/erc20.service.ts
Labels: bug, evmos

#746 fix: erc20 balance empty insert
  src/services/evm/erc20.service.ts
Labels: bug, develop

#748 fix: change type for column value out of range
  migrations/evm/20240408032348_evm_internal_tx_change_column_type.ts
Labels: develop

#749 Fix/change type table
  migrations/evm/20240408042133_evm_internal_tx_change_column_input.ts
Labels: develop

#750 fix: change type for column evm tx id
  migrations/evm/20240409065710_evm_internal_tx_change_column_evm_tx_id.ts
Labels: develop

#756 Hotfix/account balances staging
  src/services/crawl-account/crawl_account.service.ts
Labels: bug, staging

#752 fix: erc20 balance be reset to 0 in account balance
  migrations/evm/20240409100807_account_balance_add_type.ts
  src/models/account_balance.ts
  src/models/index.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/evm/erc20_handler.ts
  test/unit/services/crawl-account/crawl_account.spec.ts
Labels: bug, develop

#755 feat: erc20 proxy contract
  src/models/evm_proxy_history.ts
  src/services/evm/erc20.service.ts
  test/unit/services/erc20/erc20.spec.ts
Labels: develop

#763 feat: add status, reason to evm_transaction
  migrations/evm/20240422080742_evm_tx_create_status_col.ts
  src/models/event_attribute.ts
  src/models/evm_transaction.ts
  src/services/evm/handle_tx_evm.service.ts
Labels: develop

#707 fix: remove numberOfBlockPerCall to use blocksPerCall in crawl block, tx
  ci/config.json.ci
  config.json
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
Labels: staging

#765 Fix/improve crawl delegator from txmsg staging
  ci/config.json.ci
  config.json
  package.json
  src/common/constant.ts
  src/common/utils/aurajs_client.ts
  src/common/utils/provider.registry.ts
  src/models/delegator.ts
  src/services/crawl-validator/crawl_delegators.service.ts
  src/services/job/update_assets.service.ts
  test/unit/services/crawl-validator/crawl_delegators.spec.ts
Labels: staging

#764 hotfix: erc20-balance (incorrect conditional to get original account balance)
  src/services/evm/erc20.service.ts
Labels: bug, develop

#757 Hotfix/account balances main
  src/services/crawl-account/crawl_account.service.ts
Labels: bug, main

#766 Hotfix/erc20 balance staging (incorrect conditional to get original account balance)
  src/services/evm/erc20.service.ts
Labels: bug, staging

#761 Fix/erc20 proxy contract
  ci/config.json.ci
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc20.service.ts
  test/unit/services/evm/crawl_evm_proxy_history.spec.ts
Labels: bug, develop

#771 feat: allow verify evm contract match partial
  src/services/evm/verify_contract_evm.service.ts
Labels: staging

#768 Fix/erc20 proxy contract staging
  ci/config.json.ci
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc20.service.ts
  test/unit/services/evm/crawl_evm_proxy_history.spec.ts
Labels: bug, staging

#772 feat: remove throw Error to continue verify all contract evm
  src/services/evm/verify_contract_evm.service.ts
Labels: staging

#773 fix: insert empty erc20 contract
  src/services/evm/erc20.service.ts
Labels: bug, develop

#770 feat: handle erc721 proxy contracts
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc721.service.ts
  test/unit/services/evm/crawl_evm_proxy_history.spec.ts
Labels: develop

#751 feat: erc721 activity + token
  ci/config.json.ci
  config.json
  migrations/evm/20240409065017_erc721_token_init.ts
  migrations/evm/20240409065018_erc721_activity_init.ts
  src/models/erc721_activity.ts
  src/models/erc721_token.ts
  src/models/index.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc721.service.ts
  src/services/evm/erc721_handler.ts
  test/unit/services/erc721/erc721.spec.ts
  test/unit/services/evm/crawl_evm_proxy_history.spec.ts
Labels: develop
