Repository aura-nw/horoscope-v2, pull requests merged in 2024-01, with the labels that each got.

#567 feat: horoscope handler (staging)
  src/common/constant.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/horoscope_handler.service.ts
  src/services/horoscope-handler/handler.service.ts
Labels: staging

#562 feat: chain registries
  ci/config.json.ci
  config.json
  package-lock.json
  package.json
  src/common/constant.ts
  src/common/utils/chain.registry.ts
  src/common/utils/provider.registry.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-tx/registry-type/sei-network.json
  src/services/job/reassign_msg_index_to_event.service.ts
  src/services/job/redecode_tx.service.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/job/reassign_msg_index_to_event.spec.ts
Labels: develop

#573 Fix/fix aurajs client develop
  ci/config.json.ci
  config.json
  src/common/constant.ts
  src/common/types/interfaces.ts
  src/common/utils/aurajs_client.ts
  src/common/utils/provider.registry.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-proposal/crawl_proposal.service.ts
  src/services/crawl-proposal/crawl_tally_proposal.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-validator/crawl_delegators.service.ts
  src/services/crawl-validator/crawl_signing_info.service.ts
  src/services/crawl-validator/crawl_validator.service.ts
  src/services/statistics/dashboard_statistics.service.ts
Labels: develop

#575 Feat/partition for block
  ci/config.json.ci
  config.json
  hasura/metadata/databases/auratestnet/tables/public_block.yaml
  hasura/metadata/databases/auratestnet/tables/public_block_signature.yaml
  hasura/metadata/databases/auratestnet/tables/public_event.yaml
  hasura/metadata/databases/auratestnet/tables/public_event_attribute.yaml
  hasura/metadata/databases/auratestnet/tables/public_transaction.yaml
  hasura/metadata/databases/euphoria/tables/public_block.yaml
  hasura/metadata/databases/euphoria/tables/public_block_signature.yaml
  hasura/metadata/databases/euphoria/tables/public_event.yaml
  hasura/metadata/databases/euphoria/tables/public_event_attribute.yaml
  hasura/metadata/databases/euphoria/tables/public_transaction.yaml
  hasura/metadata/databases/pacific/tables/public_block.yaml
  hasura/metadata/databases/pacific/tables/public_block_signature.yaml
  hasura/metadata/databases/sei/tables/public_block.yaml
  hasura/metadata/databases/sei/tables/public_block_signature.yaml
  hasura/metadata/databases/serenity/tables/public_block.yaml
  hasura/metadata/databases/serenity/tables/public_block_signature.yaml
  hasura/metadata/databases/serenity/tables/public_event.yaml
  hasura/metadata/databases/serenity/tables/public_event_attribute.yaml
  hasura/metadata/databases/serenity/tables/public_transaction.yaml
  hasura/metadata/databases/xstaxy/tables/public_block.yaml
  hasura/metadata/databases/xstaxy/tables/public_block_signature.yaml
  hasura/metadata/databases/xstaxy/tables/public_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_event_attribute.yaml
  hasura/metadata/databases/xstaxy/tables/public_transaction.yaml
  migrations/20240103081215_partition-block-table.ts
  src/common/constant.ts
  src/services/job/create_block_partition.service.ts
  test/unit/services/crawl-account/handle_address.spec.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-cosmwasm/crawl_smart_contract.spec.ts
  test/unit/services/crawl-proposal/crawl_proposal.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/crawl-validator/crawl_validator.spec.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
  test/unit/services/handle-vote/handle_vote.spec.ts
  test/unit/services/ibc/crawl_ibc_app.spec.ts
  test/unit/services/ibc/crawl_ibc_ics20.spec.ts
  test/unit/services/ibc/crawl_ibc_tao.spec.ts
Labels: develop

#577 feat: add tx_count to block; use tx_count to pagination in crawl_tx (sei)
  migrations/20240105040723_add_tx_count_to_block.ts
  migrations/20240105075722_drop_transaction_message_receiver.ts
  src/models/block.ts
  src/models/index.ts
  src/models/transaction_message.ts
  src/models/transaction_message_receiver.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: sei

#579 feat: create hasura metadata
  .env.hasura.sample
  .github/workflows/ci.yml
  .gitignore
  Dockerfile.hasura
  README.md
  hasura/config.yaml
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  hasura/metadata/allow_list.yaml
  hasura/metadata/cron_triggers.yaml
  hasura/metadata/databases/databases.yaml
  hasura/metadata/query_collections.yaml
  hasura/metadata/remote_schemas.yaml
  hasura/metadata/version.yaml
Labels: main

#580 Refactor/handle ibc ack for sei
  src/services/ibc/crawl_ibc_ics20.service.ts
  test/unit/services/ibc/crawl_ibc_ics20.spec.ts
Labels: sei

#588 fix: update tx_msg in job crawl_tx
  ci/config.json.ci
  config.json
  src/services/crawl-tx/crawl_tx.service.ts
Labels: sei

#586 feat: create tx_id column in smart_contract_event
  migrations/20240110032646_create_tx_id_column_in_smart_contract_event.ts
  src/common/utils/smart_contract.ts
  src/models/smart_contract_event.ts
  src/services/crawl-cosmwasm/crawl_contract_event.service.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: develop

#587 Feat/create tx id column in smart contract event merge sei
  migrations/20240110032646_create_tx_id_column_in_smart_contract_event.ts
  src/common/utils/smart_contract.ts
  src/models/smart_contract_event.ts
  src/services/crawl-cosmwasm/crawl_contract_event.service.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: sei

#555 Fix/add authz to coin transfer (main)
  src/services/crawl-tx/coin_transfer.service.ts
  test/unit/services/crawl-transaction/authz_tx_coin_transfer.json
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
Labels: main

#603 feat: add tx count; remove old code not used in crawl_tx
  ci/config.json.ci
  config.json
  migrations/20240105040723_add_tx_count_to_block.ts
  migrations/20240105075722_drop_transaction_message_receiver.ts
  src/common/constant.ts
  src/models/block.ts
  src/models/index.ts
  src/models/transaction_message.ts
  src/models/transaction_message_receiver.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: develop

#604 feat: add concurrency to job HANDLE_CW721_TOKEN_MEDIA
  ci/config.json.ci
  config.json
  src/services/cw721/cw721-media.service.ts
Labels: develop

#582 Refactor/handle ibc ack for sei
  src/services/ibc/crawl_ibc_ics20.service.ts
  test/unit/services/ibc/crawl_ibc_ics20.spec.ts
Labels: develop

#607 feat: add concurrency to job HANDLE_CW721_TOKEN_MEDIA
  ci/config.json.ci
  config.json
  src/services/cw721/cw721-media.service.ts
Labels: staging

#611 feat: add statement_timeout config to knex
  .env.sample
  knexfile.ts
Labels: develop

#612 feat: add statement_timeout config to knex
  .env.sample
  knexfile.ts
Labels: staging

#613 feat: add statement_timeout config to knex
  .env.sample
  knexfile.ts
Labels: main

#605 Fix/update query handle stake event
  src/services/crawl-validator/handle_stake_event.service.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
Labels: staging

#591 feat: upload raw log block to s3
  ci/config.json.ci
  config.json
  src/common/constant.ts
  src/common/utils/utils.ts
  src/services/crawl-block/upload_block_raw_log_to_s3.service.ts
Labels: develop

#621 Feat/partition for transaction
  ci/config.json.ci
  config.json
  hasura/metadata/databases/euphoria/tables/public_event.yaml
  hasura/metadata/databases/euphoria/tables/public_event_attribute.yaml
  hasura/metadata/databases/euphoria/tables/public_feegrant.yaml
  hasura/metadata/databases/euphoria/tables/public_feegrant_history.yaml
  hasura/metadata/databases/euphoria/tables/public_power_event.yaml
  hasura/metadata/databases/euphoria/tables/public_transaction_message.yaml
  hasura/metadata/databases/euphoria/tables/public_vote.yaml
  hasura/metadata/databases/xstaxy/tables/public_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_event_attribute.yaml
  hasura/metadata/databases/xstaxy/tables/public_feegrant.yaml
  hasura/metadata/databases/xstaxy/tables/public_feegrant_history.yaml
  hasura/metadata/databases/xstaxy/tables/public_power_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_transaction_message.yaml
  hasura/metadata/databases/xstaxy/tables/public_vote.yaml
  migrations/20231129081016_partition-transaction-table.ts
  src/common/constant.ts
  src/models/ibc_message.ts
  src/services/job/create_constraint_in_transaction_partition.service.ts
  src/services/job/create_index_composite_in_attr_partition.service.ts
  src/services/job/create_transaction_partition.service.ts
  test/unit/services/crawl-account/handle_address.spec.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-cosmwasm/crawl_smart_contract.spec.ts
  test/unit/services/crawl-proposal/crawl_proposal.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/crawl-validator/crawl_validator.spec.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
  test/unit/services/handle-vote/handle_vote.spec.ts
  test/unit/services/ibc/crawl_ibc_app.spec.ts
  test/unit/services/ibc/crawl_ibc_ics20.spec.ts
  test/unit/services/ibc/crawl_ibc_tao.spec.ts
  test/unit/services/job/create_constraint_transaction_partition.spec.ts
  test/unit/services/job/create_table_event_partition.spec.ts
  test/unit/services/job/create_table_transaction_partition.spec.ts
  test/unit/services/job/reassign_msg_index_to_event.spec.ts
Labels: staging

#620 feat: change totalBlocks in dashboard statistic to use handle_transaction block_checkpoint
  src/services/statistics/dashboard_statistics.service.ts
Labels: develop

#624 fix: add forEach to update balance query in account
  src/services/crawl-account/crawl_account.service.ts
Labels: main

#615 feat: alter coin amount; fix: support old cw721 contract (not has info field)
  migrations/20240103025940_update_type_amount_in_coin_transfer.ts
  src/models/coin_transfer.ts
  src/services/cw721/cw721-media.service.ts
Labels: staging

#618 feat: create job update tx count
  ci/config.json.ci
  config.json
  src/common/constant.ts
  src/services/job/update_tx_count_in_block.service.ts
Labels: develop

#606 fix: update query handle stake event
  src/services/crawl-validator/handle_stake_event.service.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
Labels: main

#630 fix: split tx registry to json
  src/services/crawl-tx/aura.registry.ts
  src/services/crawl-tx/registry-type/aura-network.json
Labels: main

#626 feat: change totalBlocks to use handle_transaction block_checkpoint
  src/services/statistics/dashboard_statistics.service.ts
Labels: staging

#614 feat: alter coin amount; fix: support old cw721 contract (not has info field)
  migrations/20240103025940_update_type_amount_in_coin_transfer.ts
  src/models/coin_transfer.ts
  src/services/cw721/cw721-media.service.ts
Labels: main

#627 feat: change totalBlocks to use handle_transaction block_checkpoint
  src/services/statistics/dashboard_statistics.service.ts
Labels: main

#608 feat: add concurrency to job HANDLE_CW721_TOKEN_MEDIA
  ci/config.json.ci
  config.json
  src/services/cw721/cw721-media.service.ts
Labels: main

#631 Feat/chain registry staging
  package-lock.json
  package.json
  src/common/constant.ts
  src/common/utils/chain.registry.ts
  src/common/utils/provider.registry.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-tx/registry-type/sei-network.json
  src/services/job/reassign_msg_index_to_event.service.ts
  src/services/job/redecode_tx.service.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/job/reassign_msg_index_to_event.spec.ts
Labels: staging

#632 Feat/partition block for staging
  ci/config.json.ci
  config.json
  hasura/metadata/databases/euphoria/tables/public_block.yaml
  hasura/metadata/databases/euphoria/tables/public_block_signature.yaml
  hasura/metadata/databases/euphoria/tables/public_event.yaml
  hasura/metadata/databases/euphoria/tables/public_event_attribute.yaml
  hasura/metadata/databases/xstaxy/tables/public_block.yaml
  hasura/metadata/databases/xstaxy/tables/public_block_signature.yaml
  hasura/metadata/databases/xstaxy/tables/public_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_event_attribute.yaml
  migrations/20240103081215_partition-block-table.ts
  src/common/constant.ts
  src/services/job/create_block_partition.service.ts
  test/unit/services/crawl-account/handle_address.spec.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-cosmwasm/crawl_smart_contract.spec.ts
  test/unit/services/crawl-proposal/crawl_proposal.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/crawl-validator/crawl_validator.spec.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
  test/unit/services/handle-vote/handle_vote.spec.ts
  test/unit/services/ibc/crawl_ibc_app.spec.ts
  test/unit/services/ibc/crawl_ibc_ics20.spec.ts
  test/unit/services/ibc/crawl_ibc_tao.spec.ts
Labels: staging

#616 fix: handle missing code id
  src/services/crawl-cosmwasm/crawl_smart_contract.service.ts
Labels: develop

#634 Feat/upload raw block tx to s3
  ci/config.json.ci
  config.json
  src/common/constant.ts
  src/common/utils/utils.ts
  src/services/crawl-block/upload_block_raw_log_to_s3.service.ts
Labels: staging

#633 feat: update aurajs client; add tx count; remove transaction_message; split job crawl_tx
  ci/config.json.ci
  config.json
  migrations/20240105040723_add_tx_count_to_block.ts
  migrations/20240105075722_drop_transaction_message_receiver.ts
  src/common/constant.ts
  src/common/types/interfaces.ts
  src/common/utils/aurajs_client.ts
  src/common/utils/provider.registry.ts
  src/models/block.ts
  src/models/index.ts
  src/models/transaction_message.ts
  src/models/transaction_message_receiver.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-proposal/crawl_proposal.service.ts
  src/services/crawl-proposal/crawl_tally_proposal.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
  src/services/crawl-validator/crawl_delegators.service.ts
  src/services/crawl-validator/crawl_signing_info.service.ts
  src/services/crawl-validator/crawl_validator.service.ts
  src/services/job/update_tx_count_in_block.service.ts
  src/services/statistics/dashboard_statistics.service.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: staging

#576 feat: partition transaction message (develop)
  ci/config.json.ci
  config.json
  migrations/20240103082700_transaction_message_partition.ts
  src/common/constant.ts
  src/services/job/create_constraint_in_transaction_message_partition.service.ts
  src/services/job/create_transaction_message_partition.service.ts
  test/unit/services/job/create_constraint_transaction_message_partition.spec.ts
  test/unit/services/job/create_table_transaction_message_partition.spec.ts
Labels: develop

#641 fix: update return condition in crawl_tx and handle_tx job
  src/services/crawl-tx/crawl_tx.service.ts
Labels: develop

#642 fix: update return condition in crawl_tx and handle_tx job
  src/services/crawl-tx/crawl_tx.service.ts
Labels: staging

#643 fix: update return condition in crawl_tx and handle_tx job
  src/services/crawl-tx/crawl_tx.service.ts
Labels: main

#644 Feat/partition for event main
  ci/config.json.ci
  config.json
  hasura/metadata/databases/xstaxy/tables/public_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_event_attribute.yaml
  hasura/metadata/databases/xstaxy/tables/public_smart_contract_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_view_ibc_channel_detail_statistic.yaml
  migrations/20231121021951_create_table_event_partition.ts
  package.json
  src/common/constant.ts
  src/services/job/create_constraint_in_event_partition.service.ts
  src/services/job/create_event_partition.service.ts
  src/services/job/migrate_data_event_table.service.ts
  src/services/job/rename_event_with_event_partition.service.ts
  test/unit/mock-data/block.mock.ts
  test/unit/mock-data/event.mock.ts
  test/unit/mock-data/transaction.mock.ts
  test/unit/services/job/create_constraint_event_partition.spec.ts
  test/unit/services/job/create_table_event_partition.spec.ts
  test/unit/services/job/migrate_data_event_table.spec.ts
Labels: main
