Repository aura-nw/horoscope-v2, pull requests merged in 2024-07, with the labels that each got.

#818 feat: hanlde selfdestruct contract
  migrations/evm/20240619100559_evm_smart_contract_add_status.ts
  src/models/evm_internal_transaction.ts
  src/models/evm_smart_contract.ts
  src/models/evm_transaction.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  test/unit/services/evm/crawl_contract_evm.spec.ts
Labels: develop

#827 feat: add date to evm_tx
  migrations/evm/20240626081027_add_date_to_evm_tx.ts
  src/models/evm_block.ts
  src/models/evm_transaction.ts
  src/services/evm/crawl_evm_block.service.ts
  src/services/evm/crawl_evm_transaction.service.ts
  test/unit/services/evm/crawl_evm_transaction.spec.ts
Labels: evm

#831 fix: add handle eth_account in account auth
  src/common/constant.ts
  src/models/account.ts
  src/services/crawl-account/crawl_account.service.ts
Labels: develop

#832 fix: erc721 stats fail because of EvmBlock
  src/services/evm/erc721_handler.ts
  test/unit/services/erc721/erc721_handler.spec.ts
Labels: evm

#836 refactor: crawl internal tx from to nullable
  migrations/evm/20240703033416_evm_internal_transaction_from_to_nullable.ts
Labels: staging

#834 fix: add handle eth_account in account auth
  src/common/constant.ts
  src/models/account.ts
  src/services/crawl-account/crawl_account.service.ts
Labels: staging

#826 feat: evm statistic
  ci/config.json.ci
  config.json
  src/models/evm_transaction.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/evm_statistics.service.ts
  src/services/evm/constant.ts
  src/services/evm/statistic/account_statistics.service.ts
  src/services/evm/statistic/api_statistics.service.ts
  src/services/evm/statistic/daily_statistics.service.ts
  src/services/evm/statistic/daily_stats_jobs.service.ts
  src/services/evm/statistic/dashboard_statistics.service.ts
Labels: evm

#837 Fix/crawl internal tx call error main
  migrations/evm/20240613070822_evm_internal_transaction_add_error_col.ts
  migrations/evm/20240703033416_evm_internal_transaction_from_to_nullable.ts
  src/models/evm_internal_transaction.ts
  src/services/evm/evm_crawl_internal_tx.service.ts
Labels: main

#835 fix: add handle eth_account in account auth
  src/common/constant.ts
  src/models/account.ts
  src/services/crawl-account/crawl_account.service.ts
Labels: main

#838 Refactor/repalce etherjs by viem main
  package-lock.json
  package.json
  src/common/utils/etherjs_client.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/crawl_evm_proxy_history.service.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc721.service.ts
  src/services/evm/evm_proxy.service.ts
  src/services/evm/handle_tx_evm.service.ts
  src/services/evm/helpers/contract_helper.ts
  src/services/evm/verify_contract_evm.service.ts
  test/unit/services/evm/evm_proxy.spec.ts
Labels: main

#840 feat: add api gateway to query evm statistics
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/evm_statistics.service.ts
Labels: develop

#841 Feat/self destruct contract staging
  migrations/evm/20240619100559_evm_smart_contract_add_status.ts
  src/models/evm_internal_transaction.ts
  src/models/evm_smart_contract.ts
  src/models/evm_transaction.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  test/unit/services/evm/crawl_contract_evm.spec.ts
Labels: staging

#839 feat: erc20 track deposit & withdrawal
  ci/config.json.ci
  config.json
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  test/unit/services/erc20/erc20_handler.spec.ts
Labels: develop

#828 feat: handle cosmos convertCoin, convertErc20 in job erc20Activity
  ci/config.json.ci
  config.json
  migrations/evm/20240702013020_add_col_to_save_cosmos_erc20.ts
  src/models/erc20_activity.ts
  src/models/event.ts
  src/models/event_attribute.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
Labels: develop

#829 refactor: crawl evm contract loop & batch request bytecode contracts
  src/services/evm/crawl_contract_evm.service.ts
Labels: develop

#833 feat: crawl optimism deposit from l1
  ci/config.json.ci
  config.json
  migrations/evm/20240704062127_optimism_deposit.ts
  network.json
  src/common/utils/etherjs_client.ts
  src/models/index.ts
  src/models/optimism_deposit.ts
  src/services/evm/constant.ts
  src/services/evm/optimism/deposit.service.ts
Labels: evm

#843 feat: pino log discord & handle throw
  package-lock.json
  package.json
  src/common/queue/queue-manager.ts
  src/moleculer.config.ts
Labels: develop

#846 fix: cw721 stats error
  src/services/cw721/cw721.service.ts
Labels: bug, develop

#845 feat: add l1 fee to evm tx
  ci/config.json.ci
  config.json
  migrations/evm/20240712041542_add_l1_fee_to_evm_tx.ts
  src/models/evm_transaction.ts
  src/services/evm/crawl_evm_transaction.service.ts
  test/unit/services/evm/crawl_evm_transaction.spec.ts
Labels: evm

#844 feat: add erc20 activity from cosmos tx
  ci/config.json.ci
  config.json
  migrations/evm/20240702013020_add_col_to_save_cosmos_erc20.ts
  src/models/erc20_activity.ts
  src/models/event.ts
  src/models/event_attribute.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
Labels: staging

#849 fix: cw20 notfound error
  src/services/cw20/cw20.service.ts
Labels: bug, develop

#848 refactor: discord log stack trace and throw error when meet error
  src/common/queue/queue-manager.ts
Labels: develop

#822 test: complete test
  src/services/evm/erc20.service.ts
  src/services/evm/erc721.service.ts
  src/services/evm/handle_tx_evm.service.ts
  test/unit/services/cw721/cw721.spec.ts
  test/unit/services/erc20/erc20.spec.ts
  test/unit/services/evm/erc20.spec.ts
  test/unit/services/evm/erc20_handler.spec.ts
  test/unit/services/evm/erc721-media.spec.ts
  test/unit/services/evm/erc721.spec.ts
  test/unit/services/evm/erc721_handler.spec.ts
  test/unit/services/evm/evm_crawl_internal_tx.spec.ts
  test/unit/services/evm/evm_proxy.spec.ts
  test/unit/services/evm/evm_signature_mapping.spec.ts
  test/unit/services/evm/handle_tx_evm.spec.ts
Labels: develop

#842 feat: optimism withdrawal
  ci/config.json.ci
  config.json
  migrations/evm/20240708071121_optimism_withdrawal.ts
  migrations/evm/20240712041542_add_l1_fee_to_evm_tx.ts
  src/common/types/interfaces.ts
  src/common/utils/db_connection.ts
  src/common/utils/etherjs_client.ts
  src/models/evm_transaction.ts
  src/models/index.ts
  src/models/optimism_withdrawal.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_evm_transaction.service.ts
  src/services/evm/optimism/withdrawal.service.ts
  test/unit/services/evm/crawl_evm_transaction.spec.ts
Labels: evm

#853 feat: self destruct contract merge evm
  migrations/evm/20240619100559_evm_smart_contract_add_status.ts
  src/models/evm_internal_transaction.ts
  src/models/evm_smart_contract.ts
  src/models/evm_transaction.ts
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  test/unit/services/evm/crawl_contract_evm.spec.ts
Labels: evm

#854 refactor: crawl evm contract merge evm
  src/services/evm/crawl_contract_evm.service.ts
Labels: evm

#861 feat: add optimism withdrawal finalize time
  migrations/evm/20240723063129_add_finalize_time_to_op_withdrawal.ts
  src/models/optimism_withdrawal.ts
  src/services/evm/optimism/withdrawal.service.ts
Labels: evm

#851 Feat/erc20 reindexing
  src/models/account_balance.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/erc20_admin.service.ts
  src/services/evm/constant.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  src/services/evm/erc20_reindex.ts
  test/unit/services/evm/erc20_handler.spec.ts
  test/unit/services/evm/erc20_reindex.spec.ts
Labels: develop

#857 Hotfix: crawl evm contract
  src/services/evm/crawl_contract_evm.service.ts
Labels: bug, develop

#858 hotfix: crawl evm contract
  src/services/evm/crawl_contract_evm.service.ts
Labels: bug, staging

#862 fix: order erc20 activities
  src/services/evm/erc20_handler.ts
  test/unit/services/evm/erc20_handler.spec.ts
Labels: bug, develop

#864 refactor: network json add ancient8
  network.json
Labels: develop

#866 Feat/erc20 track deposit withdraw staging
  ci/config.json.ci
  config.json
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  test/unit/services/erc20/erc20_handler.spec.ts
Labels: staging

#863 fix: erc20 update total supply
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  test/unit/services/evm/erc20_handler.spec.ts
  test/unit/services/evm/erc20_reindex.spec.ts
Labels: bug, develop

#867 fix: evm account mising
  src/services/evm/crawl_evm_account.service.ts
  src/services/evm/crawl_evm_event.service.ts
Labels: bug, evm

#868 fix: erc20 reindex totalSupply
  src/services/evm/erc20_reindex.ts
Labels: develop

#875 feat: merge erc20 from develop to staging
  src/models/account_balance.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/erc20_admin.service.ts
  src/services/evm/constant.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  src/services/evm/erc20_reindex.ts
  test/unit/services/erc20/erc20.spec.ts
  test/unit/services/erc20/erc20_handler.spec.ts
  test/unit/services/evm/erc20.spec.ts
  test/unit/services/evm/erc20_handler.spec.ts
  test/unit/services/evm/erc20_reindex.spec.ts
Labels: staging

#874 feat: merge erc20 from develop to main
  ci/config.json.ci
  config.json
  migrations/evm/20240702013020_add_col_to_save_cosmos_erc20.ts
  src/models/account_balance.ts
  src/models/erc20_activity.ts
  src/models/event.ts
  src/models/event_attribute.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/erc20_admin.service.ts
  src/services/evm/constant.ts
  src/services/evm/erc20.service.ts
  src/services/evm/erc20_handler.ts
  src/services/evm/erc20_reindex.ts
  test/unit/services/erc20/erc20.spec.ts
  test/unit/services/erc20/erc20_handler.spec.ts
  test/unit/services/evm/erc20.spec.ts
  test/unit/services/evm/erc20_handler.spec.ts
  test/unit/services/evm/erc20_reindex.spec.ts
Labels: main

#876 fix: test ci
  test/unit/services/evm/erc20_handler.spec.ts
Labels: develop
