Repository aura-nw/horoscope-v2, pull requests merged in 2024-03, with the labels that each got.

#654 feat: upload raw tx to s3 (staging)
  ci/config.json.ci
  config.json
  src/common/constant.ts
  src/services/crawl-tx/upload_tx_raw_log_to_s3.service.ts
Labels: staging

#675 feat: add index (height, index) to transaction to optimize tx contract (develop)
  hasura/metadata/databases/auratestnet/tables/public_transaction.yaml
  hasura/metadata/databases/euphoria/tables/public_transaction.yaml
  hasura/metadata/databases/evmostestnet/tables/public_transaction.yaml
  hasura/metadata/databases/serenity/tables/public_transaction.yaml
  hasura/metadata/databases/xstaxy/tables/public_transaction.yaml
  migrations/20240304070916_create_composite_index_height_index_in_tx.ts
Labels: develop

#674 feat: evm event
  ci/config.json.ci
  config.json
  migrations/20240227083112_evm_event.ts
  src/common/constant.ts
  src/models/evm_event.ts
  src/models/index.ts
  src/services/handle-evm-event/crawl_evm_event.service.ts
Labels: evmos

#676 feat: add index (height, index) to transaction to optimize query tx contract (staging)
  migrations/20240304070916_create_composite_index_height_index_in_tx.ts
Labels: staging

#677 feat: add index (height, index) to transaction to optimize query tx contract
  hasura/metadata/databases/xstaxy/tables/public_transaction.yaml
  migrations/20240304070916_create_composite_index_height_index_in_tx.ts
Labels: main

#657 Fix/improve crawl delegator from txmsg
  ci/config.json.ci
  config.json
  package-lock.json
  package.json
  src/common/constant.ts
  src/common/utils/aurajs_client.ts
  src/common/utils/provider.registry.ts
  src/models/delegator.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/job.service.ts
  src/services/crawl-validator/crawl_delegators.service.ts
  src/services/job/update_assets.service.ts
  test/unit/services/crawl-validator/crawl_delegators.spec.ts
Labels: develop

#683 feat: init crawl evm contract
  ci/config.json.ci
  config.json
  migrations/20240307101458_create_evm_smart_contract.ts
  network.json
  package-lock.json
  package.json
  src/common/constant.ts
  src/common/utils/etherjs_client.ts
  src/models/evm_event.ts
  src/models/evm_smart_contract.ts
  src/models/index.ts
  src/services/handle-tx-evm/constant.ts
  src/services/handle-tx-evm/crawl_contract_evm.service.ts
  src/services/handle-tx-evm/handle_tx_evm.service.ts
Labels: evmos

#682 Feat/table asset staging
  ci/config.json.ci
  config.json
  migrations/20240110065150_create_asset_model.ts
  src/common/constant.ts
  src/models/asset.ts
  src/services/job/update_assets.service.ts
  test/unit/services/job/update_assets.spec.ts
Labels: staging

#684 feat: convert address is lowercase in crawl event evm
  src/services/handle-evm-event/crawl_evm_event.service.ts
  src/services/handle-tx-evm/crawl_contract_evm.service.ts
Labels: evmos

#680 feat: create api and job verify contract evm (evmos)
  ci/config.json.ci
  ci/network.json.ci
  config.json
  migrations/20240305072734_create_table_evm_contract_verification.ts
  package-lock.json
  package.json
  src/common/constant.ts
  src/models/evm_contract_verification.ts
  src/models/index.ts
  src/services/api-gateways/api_gateway.service.ts
  src/services/api-gateways/verify_contract_evm.service.ts
  src/services/verify-contract-evm/solidity_compiler.ts
  src/services/verify-contract-evm/verify_contract_evm.service.ts
  test/unit/services/verify-contract-evm/erc721.zip
  test/unit/services/verify-contract-evm/expected_compile_erc721.json
  test/unit/services/verify-contract-evm/expected_compile_storage.json
  test/unit/services/verify-contract-evm/storage.zip
  test/unit/services/verify-contract-evm/verify_contract_evm.spec.ts
Labels: evmos

#679 Feat/cw721 contract statistic
  ci/config.json.ci
  config.json
  migrations/20240304035658_cw721_contract_statistic.ts
  src/common/constant.ts
  src/models/cw721_contract.ts
  src/services/cw721/cw721-reindexing.service.ts
  src/services/cw721/cw721.service.ts
  src/services/cw721/cw721_handler.ts
  test/unit/services/cw721/cw721.spec.ts
Labels: develop

#687 feat: detect erc20, erc721, erc1155 by interface in bytecode
  src/models/evm_smart_contract.ts
  src/services/handle-tx-evm/constant.ts
  src/services/handle-tx-evm/crawl_contract_evm.service.ts
Labels: evmos

#690 feat: alter type bigint to decimal in account_statistics
  migrations/20240314021935_alter_type_account_statistics.ts
Labels: evmos

#685 fix: crawl evm_contract with tx create contract not emit event
  migrations/20240311063708_add_col_contract_address_to_evm_tx.ts
  migrations/20240312040758_add_col_code_hash_to_evm_contract.ts
  src/models/evm_event.ts
  src/models/evm_smart_contract.ts
  src/models/evm_transaction.ts
  src/services/handle-tx-evm/constant.ts
  src/services/handle-tx-evm/crawl_contract_evm.service.ts
  src/services/handle-tx-evm/handle_tx_evm.service.ts
Labels: evmos

#694 refactor: upgrade typescript from 4.8.4 to 5.4.2
  package-lock.json
  package.json
  tsconfig-base.json
Labels: dependencies, evmos

#697 Refactor/upgrade typescript from 4.8.4 to 5.4.: fix build
  package-lock.json
  package.json
  tsconfig-base.json
Labels: bug, evmos

#700 feat: merge all evm service into one folder
  src/services/evm/constant.ts
  src/services/evm/crawl_contract_evm.service.ts
  src/services/evm/crawl_evm_event.service.ts
  src/services/evm/evm_signature_mapping.service.ts
  src/services/evm/handle_tx_evm.service.ts
  src/services/evm/solidity_compiler.ts
  src/services/evm/verify_contract_evm.service.ts
  test/unit/services/signature-mapping/evm_signature_mapping.spec.ts
  test/unit/services/verify-contract-evm/verify_contract_evm.spec.ts
Labels: evmos

#689 feat: add precompiles contracts
  migrations/20240318035604_add-precompiles-comtracts.ts
  src/services/evm/precompile-abis/bank.json
  src/services/evm/precompile-abis/bech32.json
  src/services/evm/precompile-abis/distribution.json
  src/services/evm/precompile-abis/ics20.json
  src/services/evm/precompile-abis/staking.json
  src/services/evm/precompile-abis/vesting.json
Labels: evmos

#703 fix: remove insert conflict do nothing tin crawl contract evm
  src/services/evm/crawl_contract_evm.service.ts
Labels: evmos

#699 fix: remove numberOfBlockPerCall to use blocksPerCall in crawl block, tx
  ci/config.json.ci
  config.json
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
Labels: evmos

#706 fix: remove numberOfBlockPerCall to use blocksPerCall in crawl block, tx
  ci/config.json.ci
  config.json
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
Labels: develop

#713 fix: erc20 missing view function
  src/services/evm/erc20.service.ts
Labels: bug, evmos

#711 feat: create index to optimize query tx in account detail aurascan
  migrations/20240320074436_create_index_owner_not_burned_cw721_token.ts
  migrations/20240320084001_create_tx_id_in_cw20_activity.ts
  migrations/20240321015030_create_composite_index_tx_id_sender_in_tx_msg.ts
  src/models/cw20_activity.ts
  src/services/cw20/cw20.service.ts
Labels: develop

#717 feat: create index to optimize query tx in account detail aurascan
  migrations/20240320074436_create_index_owner_not_burned_cw721_token.ts
  migrations/20240320084001_create_tx_id_in_cw20_activity.ts
  migrations/20240321015030_create_composite_index_tx_id_sender_in_tx_msg.ts
  src/models/cw20_activity.ts
  src/services/cw20/cw20.service.ts
Labels: staging

#652 feat: crawl block for evmos (develop)
  src/models/event.ts
  src/models/event_attribute.ts
  src/services/crawl-block/crawl_block.service.ts
  src/services/crawl-tx/crawl_tx.service.ts
Labels: develop

#716 Feat/table asset main
  ci/config.json.ci
  config.json
  migrations/20240110065150_create_asset_model.ts
  src/common/constant.ts
  src/models/asset.ts
  src/services/job/update_assets.service.ts
  test/unit/services/job/update_assets.spec.ts
Labels: main

#718 feat: create index to optimize query tx in account detail aurascan
  migrations/20240320074436_create_index_owner_not_burned_cw721_token.ts
  migrations/20240320084001_create_tx_id_in_cw20_activity.ts
  migrations/20240321015030_create_composite_index_tx_id_sender_in_tx_msg.ts
  src/models/cw20_activity.ts
  src/services/cw20/cw20.service.ts
Labels: main

#720 refactor: erc20 activity from/to convert to lowercase
  src/services/evm/erc20_handler.ts
  test/unit/services/erc20/erc20_handler.spec.ts
Labels: evmos

#723 feat: evm proxy contract migration
  migrations/20240320080140_create-evm-proxy-history.ts
  src/models/evm_proxy_history.ts
Labels: evmos

#721 fix: update from in evm_tx as eth address 0x
  package-lock.json
  package.json
  src/services/evm/handle_tx_evm.service.ts
  src/services/evm/utils.ts
  test/unit/services/utils/address_converter.spec.ts
Labels: evmos

#724 fix: detect create contract if has contract_address field
  src/services/evm/crawl_contract_evm.service.ts
Labels: evmos

#672 feat: create evm_address in account table (evmos)
  migrations/20240229065959_create_evm_address_column_in_account.ts
  src/models/account.ts
  src/services/crawl-account/crawl_account.service.ts
  src/services/crawl-account/handle_address.service.ts
Labels: evmos

#695 feat: validate input verify evm contract
  migrations/20240314065656_create_compile_detail_evm_contract_verification.ts
  src/models/evm_contract_verification.ts
  src/services/api-gateways/verify_contract_evm.service.ts
  src/services/evm/verify_contract_evm.service.ts
Labels: evmos

#728 feat: add index column to evm_transaction
  migrations/20240328070749_create_index_column_in_evm_tx.ts
  src/models/evm_transaction.ts
  src/services/evm/handle_tx_evm.service.ts
Labels: evmos

#709 refactor: asset erc20
  src/common/constant.ts
  src/models/asset.ts
  src/services/evm/update_assets.service.ts
Labels: evmos

#731 fix: incorrect decimal column
  src/models/erc20_contract.ts
  src/services/evm/update_assets.service.ts
Labels: bug, evmos
