Repository aura-nw/horoscope-v2, pull requests merged in 2024-02, with the labels that each got.

#593 feat: table asset
  ci/config.json.ci
  config.json
  migrations/20240103081215_partition-block-table.ts
  migrations/20240110065150_create_asset_model.ts
  src/common/constant.ts
  src/models/asset.ts
  src/services/job/update_assets.service.ts
  test/unit/services/job/update_assets.spec.ts
Labels: develop

#640 feat: partition transaction message
  ci/config.json.ci
  config.json
  migrations/20240103082700_transaction_message_partition.ts
  src/common/constant.ts
  src/services/job/create_constraint_in_transaction_message_partition.service.ts
  src/services/job/create_transaction_message_partition.service.ts
  test/unit/services/job/create_constraint_transaction_message_partition.spec.ts
  test/unit/services/job/create_table_transaction_message_partition.spec.ts
Labels: staging

#646 Feat/partition transaction main
  ci/config.json.ci
  config.json
  hasura/metadata/databases/xstaxy/tables/public_block.yaml
  hasura/metadata/databases/xstaxy/tables/public_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_event_attribute.yaml
  hasura/metadata/databases/xstaxy/tables/public_feegrant.yaml
  hasura/metadata/databases/xstaxy/tables/public_feegrant_history.yaml
  hasura/metadata/databases/xstaxy/tables/public_power_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_transaction.yaml
  hasura/metadata/databases/xstaxy/tables/public_transaction_message.yaml
  hasura/metadata/databases/xstaxy/tables/public_vote.yaml
  migrations/20231129081016_partition-transaction-table.ts
  src/common/constant.ts
  src/services/job/create_constraint_in_transaction_partition.service.ts
  src/services/job/create_transaction_partition.service.ts
  test/unit/services/crawl-account/handle_address.spec.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-cosmwasm/crawl_smart_contract.spec.ts
  test/unit/services/crawl-proposal/crawl_proposal.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/crawl-validator/crawl_validator.spec.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
  test/unit/services/handle-vote/handle_vote.spec.ts
  test/unit/services/ibc/crawl_ibc_app.spec.ts
  test/unit/services/ibc/crawl_ibc_ics20.spec.ts
  test/unit/services/ibc/crawl_ibc_tao.spec.ts
  test/unit/services/job/create_constraint_transaction_partition.spec.ts
  test/unit/services/job/create_table_event_partition.spec.ts
  test/unit/services/job/create_table_transaction_partition.spec.ts
Labels: main

#647 Feat/partition block main
  ci/config.json.ci
  config.json
  hasura/metadata/databases/xstaxy/tables/public_block.yaml
  hasura/metadata/databases/xstaxy/tables/public_block_signature.yaml
  hasura/metadata/databases/xstaxy/tables/public_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_event_attribute.yaml
  migrations/20240103081215_partition-block-table.ts
  src/common/constant.ts
  src/services/job/create_block_partition.service.ts
  test/unit/services/crawl-account/handle_address.spec.ts
  test/unit/services/crawl-block/parse_block_event.spec.ts
  test/unit/services/crawl-cosmwasm/crawl_smart_contract.spec.ts
  test/unit/services/crawl-proposal/crawl_proposal.spec.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/crawl-validator/crawl_validator.spec.ts
  test/unit/services/crawl-validator/handle_stake_event.spec.ts
  test/unit/services/handle-vote/handle_vote.spec.ts
  test/unit/services/ibc/crawl_ibc_app.spec.ts
  test/unit/services/ibc/crawl_ibc_ics20.spec.ts
  test/unit/services/ibc/crawl_ibc_tao.spec.ts
Labels: main

#649 Table asset: update test
  test/unit/services/job/update_assets.spec.ts
Labels: develop

#645 feat: partition transaction message
  ci/config.json.ci
  config.json
  migrations/20240103082700_transaction_message_partition.ts
  src/common/constant.ts
  src/services/job/create_constraint_in_transaction_message_partition.service.ts
  src/services/job/create_transaction_message_partition.service.ts
  test/unit/services/job/create_constraint_transaction_message_partition.spec.ts
  test/unit/services/job/create_table_transaction_message_partition.spec.ts
Labels: main

#650 feat: create tx id column in smart contract event (staging)
  hasura/metadata/databases/euphoria/tables/public_smart_contract_event.yaml
  hasura/metadata/databases/xstaxy/tables/public_smart_contract_event.yaml
  migrations/20240110032646_create_tx_id_column_in_smart_contract_event.ts
  src/common/utils/smart_contract.ts
  src/models/smart_contract_event.ts
  src/services/crawl-cosmwasm/crawl_contract_event.service.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: staging

#651 feat: create tx id column in smart contract event (main)
  hasura/metadata/databases/xstaxy/tables/public_smart_contract_event.yaml
  migrations/20240110032646_create_tx_id_column_in_smart_contract_event.ts
  src/common/utils/smart_contract.ts
  src/models/smart_contract_event.ts
  src/services/crawl-cosmwasm/crawl_contract_event.service.ts
  test/unit/services/cw20/cw20.spec.ts
Labels: main

#660 refactor: cw721 media checkpoint for token
  src/services/cw721/cw721-media.service.ts
Labels: develop

#663 Fix/cw721 media query
  src/services/cw721/cw721-media.service.ts
  test/unit/services/cw721/cw721-media.spec.ts
Labels: develop

#662 Fix/cw721 media query staging
  src/services/cw721/cw721-media.service.ts
  test/unit/services/cw721/cw721-media.spec.ts
Labels: staging

#669 fix: remove parseInt in tokens field when crawl validator
  src/models/validator.ts
Labels: evmos

#666 feat: use msg log instead of event log (evmos)
  ci/config.json.ci
  config.json
  src/common/utils/chain.registry.ts
  src/services/crawl-tx/crawl_tx.service.ts
  test/unit/services/crawl-transaction/coin_transfer.spec.ts
  test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
  test/unit/services/crawl-transaction/parse_transaction.spec.ts
  test/unit/services/cw20/cw20.spec.ts
  test/unit/services/handle-vote/handle_vote.spec.ts
Labels: evmos

#668 feat: create evm transaction model with partition
  ci/config.json.ci
  config.json
  migrations/20240227082932_create_evm_transaction_table.ts
  src/common/constant.ts
  src/common/utils/utils.ts
  src/models/evm_transaction.ts
  src/models/index.ts
  src/services/handle-tx-evm/handle_tx_evm.service.ts
  src/services/job/create_constraint_in_evm_transaction_partition.service.ts
  src/services/job/create_evm_transaction_partition.service.ts
  test/unit/services/job/create_constraint_evm_transaction_partition.spec.ts
Labels: evmos

#670 Fix/cw721 media query main
  src/services/cw721/cw721-media.service.ts
  test/unit/services/cw721/cw721-media.spec.ts
Labels: main

#671 fix: remove parseInt in tokens field when crawl validator (develop)
  src/models/validator.ts
Labels: develop
